//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticaret.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EticaretContext : DbContext
    {
        public EticaretContext()
            : base("name=EticaretContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Siparis> Siparis { get; set; }
        public virtual DbSet<SiparisDetay> SiparisDetay { get; set; }
        public virtual DbSet<tbl_Duyuru> tbl_Duyuru { get; set; }
        public virtual DbSet<tbl_Favori> tbl_Favori { get; set; }
        public virtual DbSet<tbl_Kategori> tbl_Kategori { get; set; }
        public virtual DbSet<tbl_Kullanici> tbl_Kullanici { get; set; }
        public virtual DbSet<tbl_Marka> tbl_Marka { get; set; }
        public virtual DbSet<tbl_Mesaj> tbl_Mesaj { get; set; }
        public virtual DbSet<tbl_Rol> tbl_Rol { get; set; }
        public virtual DbSet<tbl_Sepet> tbl_Sepet { get; set; }
        public virtual DbSet<tbl_Urun> tbl_Urun { get; set; }
        public virtual DbSet<tbl_Yildiz> tbl_Yildiz { get; set; }
        public virtual DbSet<tbl_Yorum> tbl_Yorum { get; set; }
        public virtual DbSet<Ziyaretci> Ziyaretci { get; set; }
    
        public virtual ObjectResult<EnCokSatisYapanKategori_Result> EnCokSatisYapanKategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnCokSatisYapanKategori_Result>("EnCokSatisYapanKategori");
        }
    
        public virtual ObjectResult<Encoksatisyapilanurunler_Result> Encoksatisyapilanurunler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Encoksatisyapilanurunler_Result>("Encoksatisyapilanurunler");
        }
    
        public virtual ObjectResult<EnCokSepeteEklenenler_Result> EnCokSepeteEklenenler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<EnCokSepeteEklenenler_Result>("EnCokSepeteEklenenler");
        }
    
        public virtual ObjectResult<GunlukKayitSayisi_Result> GunlukKayitSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukKayitSayisi_Result>("GunlukKayitSayisi");
        }
    
        public virtual ObjectResult<GunlukUrunSiparisSayisi_Result> GunlukUrunSiparisSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukUrunSiparisSayisi_Result>("GunlukUrunSiparisSayisi");
        }
    
        public virtual ObjectResult<GunlukZiyaretciSayisi_Result> GunlukZiyaretciSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GunlukZiyaretciSayisi_Result>("GunlukZiyaretciSayisi");
        }
    
        public virtual ObjectResult<HaftalikSiparis_Result> HaftalikSiparis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HaftalikSiparis_Result>("HaftalikSiparis");
        }
    
        public virtual ObjectResult<HaftalikUye_Result> HaftalikUye()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HaftalikUye_Result>("HaftalikUye");
        }
    
        public virtual ObjectResult<HaftalikZiyaretci_Result> HaftalikZiyaretci()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<HaftalikZiyaretci_Result>("HaftalikZiyaretci");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamUrunSatis()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamUrunSatis");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamUyeKaydi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamUyeKaydi");
        }
    
        public virtual ObjectResult<Nullable<int>> ToplamZiyaretSayisi()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("ToplamZiyaretSayisi");
        }
    }
}
