//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticaret.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Siparis
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Siparis()
        {
            this.SiparisDetay = new HashSet<SiparisDetay>();
        }
    
        public int SiparisId { get; set; }
        public string SiparisNumarasi { get; set; }
        public Nullable<decimal> ToplamTutar { get; set; }
        public Nullable<int> KullaniciId { get; set; }
        public Nullable<System.DateTime> SiparisTarihi { get; set; }
    
        public virtual tbl_Kullanici tbl_Kullanici { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisDetay> SiparisDetay { get; set; }
    }
}
