//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticaret.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Duyuru
    {
        public int Duyuru_Id { get; set; }
        public string Link { get; set; }
        public string ResimURL { get; set; }
        public string Mesaj { get; set; }
    }
}
