//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eticaret.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Yildiz
    {
        public int Yildiz_Id { get; set; }
        public Nullable<int> Urun_Id { get; set; }
        public Nullable<double> Yildiz { get; set; }
    
        public virtual tbl_Urun tbl_Urun { get; set; }
    }
}
